Import("swiften_env")

myenv = swiften_env.Clone()
myenv.MergeFlags(swiften_env["SQLITE_FLAGS"])

objects = myenv.StaticObject([
			"HistoryManager.cpp",
			"SQLiteHistoryManager.cpp",
		])
swiften_env.Append(SWIFTEN_OBJECTS = [objects])
