Import("swiften_env")

myenv = swiften_env.Clone()
if myenv["target"] == "native":
	myenv.MergeFlags(swiften_env.get("SQLITE_FLAGS", {}))

if myenv["experimental"]:
	objects = myenv.SwiftenObject([
			"SQLiteHistoryStorage.cpp",
			])
	swiften_env.Append(SWIFTEN_OBJECTS = [objects])
