Import("swiften_env")

sources = [
		"ComponentHandshakeGenerator.cpp",
		"ComponentConnector.cpp",
		"ComponentSession.cpp",
		"ComponentSessionStanzaChannel.cpp",
		"CoreComponent.cpp",
		"Component.cpp",
		"ComponentXMLTracer.cpp",
	]

swiften_env.Append(SWIFTEN_OBJECTS = swiften_env.SwiftenObject(sources))
