Import("env")

myenv = env.Clone()
myenv.MergeFlags(myenv["SWIFTEN_FLAGS"])
myenv.MergeFlags(myenv["LIBIDN_FLAGS"])
myenv.MergeFlags(myenv["BOOST_FLAGS"])
myenv.MergeFlags(myenv.get("LIBXML_FLAGS", ""))
myenv.MergeFlags(myenv.get("EXPAT_FLAGS", ""))
myenv.MergeFlags(myenv["PLATFORM_FLAGS"])

myenv.Program("ParserTester", ["ParserTester.cpp"])
