Import("env")


if env["SCONS_STAGE"] == "build":
	myenv = env.Clone()
	myenv.UseFlags(myenv.get("LUA_FLAGS", {}))
	myenv.UseFlags(myenv["SWIFTEN_FLAGS"])
	myenv.UseFlags(myenv["SWIFTEN_DEP_FLAGS"])
	sources = [
		"linit.cpp",
		"Swiftob.cpp",
		"Users.cpp",
		"Commands.cpp",
		"MUCs.cpp",
		"Storage.cpp",
		"LuaCommands.cpp",
		"main.cpp"
	]
	swiftob = myenv.Program("swiftob", sources)
