Import("swiften_env", "env")

sources = [
		"OutgoingFileTransfer.cpp",
		"OutgoingSIFileTransfer.cpp",
		"IncomingFileTransfer.cpp",
		"IncomingJingleFileTransfer.cpp",
		"IncomingFileTransferManager.cpp",
		"RemoteJingleTransportCandidateSelector.cpp",
		"RemoteJingleTransportCandidateSelectorFactory.cpp",
		"LocalJingleTransportCandidateGenerator.cpp",
		"LocalJingleTransportCandidateGeneratorFactory.cpp",
		"JingleTransport.cpp",
		"JingleIncomingIBBTransport.cpp",
		"ReadBytestream.cpp",
		"WriteBytestream.cpp",
		"FileReadBytestream.cpp",
		"FileWriteBytestream.cpp",
		"SOCKS5BytestreamServer.cpp",
		"SOCKS5BytestreamServerSession.cpp",
		"SOCKS5BytestreamRegistry.cpp",
		"IBBSendSession.cpp",
		"IBBReceiveSession.cpp",
	]

swiften_env.Append(SWIFTEN_OBJECTS = swiften_env.SwiftenObject(sources))

env.Append(UNITTEST_SOURCES = [
			File("UnitTest/SOCKS5BytestreamServerSessionTest.cpp"),
			File("UnitTest/IBBSendSessionTest.cpp"),
			File("UnitTest/IBBReceiveSessionTest.cpp"),
	])
