Import("swiften_env")

sources = [
		"OutgoingFileTransfer.cpp",
		"ReadBytestream.cpp",
		"FileReadBytestream.cpp",
		"SOCKS5BytestreamServer.cpp",
		"SOCKS5BytestreamServerSession.cpp",
		"SOCKS5BytestreamRegistry.cpp",
		"IBBSendSession.cpp",
	]

swiften_env.Append(SWIFTEN_OBJECTS = swiften_env.StaticObject(sources))
