SWIFTEN_SOURCES += \
	Swiften/Serializer/PayloadSerializers/SoftwareVersionSerializer.cpp \
	Swiften/Serializer/PayloadSerializers/FullPayloadSerializerCollection.cpp \
	Swiften/Serializer/PayloadSerializers/ErrorSerializer.cpp \
	Swiften/Serializer/PayloadSerializers/MUCPayloadSerializer.cpp \
	Swiften/Serializer/PayloadSerializers/RosterSerializer.cpp \
	Swiften/Serializer/PayloadSerializers/DiscoInfoSerializer.cpp \
	Swiften/Serializer/PayloadSerializers/CapsInfoSerializer.cpp \
	Swiften/Serializer/PayloadSerializers/ResourceBindSerializer.cpp \
	Swiften/Serializer/PayloadSerializers/SecurityLabelSerializer.cpp \
	Swiften/Serializer/PayloadSerializers/SecurityLabelsCatalogSerializer.cpp \
	Swiften/Serializer/PayloadSerializers/VCardSerializer.cpp \
	Swiften/Serializer/PayloadSerializers/VCardUpdateSerializer.cpp

include Swiften/Serializer/PayloadSerializers/UnitTest/Makefile.inc
