SWIFTEN_SOURCES += \
	Swiften/Parser/PayloadParsers/BodyParser.cpp \
	Swiften/Parser/PayloadParsers/PriorityParser.cpp \
	Swiften/Parser/PayloadParsers/StatusParser.cpp \
	Swiften/Parser/PayloadParsers/StatusShowParser.cpp \
	Swiften/Parser/PayloadParsers/SoftwareVersionParser.cpp \
	Swiften/Parser/PayloadParsers/SecurityLabelParser.cpp \
	Swiften/Parser/PayloadParsers/SecurityLabelsCatalogParser.cpp \
	Swiften/Parser/PayloadParsers/DiscoInfoParser.cpp \
	Swiften/Parser/PayloadParsers/ErrorParser.cpp \
	Swiften/Parser/PayloadParsers/RosterParser.cpp \
	Swiften/Parser/PayloadParsers/ResourceBindParser.cpp \
	Swiften/Parser/PayloadParsers/VCardUpdateParser.cpp \
	Swiften/Parser/PayloadParsers/VCardParser.cpp \
	Swiften/Parser/PayloadParsers/FullPayloadParserFactoryCollection.cpp

include Swiften/Parser/PayloadParsers/UnitTest/Makefile.inc
