UNITTEST_SOURCES += \
	Swiften/Parser/PayloadParsers/UnitTest/BodyParserTest.cpp \
	Swiften/Parser/PayloadParsers/UnitTest/PriorityParserTest.cpp \
	Swiften/Parser/PayloadParsers/UnitTest/StatusShowParserTest.cpp \
	Swiften/Parser/PayloadParsers/UnitTest/SoftwareVersionParserTest.cpp \
	Swiften/Parser/PayloadParsers/UnitTest/ErrorParserTest.cpp \
	Swiften/Parser/PayloadParsers/UnitTest/RosterParserTest.cpp \
	Swiften/Parser/PayloadParsers/UnitTest/StatusParserTest.cpp \
	Swiften/Parser/PayloadParsers/UnitTest/DiscoInfoParserTest.cpp \
	Swiften/Parser/PayloadParsers/UnitTest/ResourceBindParserTest.cpp \
	Swiften/Parser/PayloadParsers/UnitTest/SecurityLabelParserTest.cpp \
	Swiften/Parser/PayloadParsers/UnitTest/SecurityLabelsCatalogParserTest.cpp \
	Swiften/Parser/PayloadParsers/UnitTest/VCardUpdateParserTest.cpp \
	Swiften/Parser/PayloadParsers/UnitTest/VCardParserTest.cpp \
	Swiften/Parser/PayloadParsers/UnitTest/RawXMLPayloadParserTest.cpp
