Import("swiften_env")

sources = [
		"IncomingJingleSession.cpp",
		"IncomingJingleSessionHandler.cpp",
		"JingleSessionManager.cpp",	
		"JingleResponder.cpp",
		"JingleSession.cpp",
	]

swiften_env.Append(SWIFTEN_OBJECTS = swiften_env.SwiftenObject(sources))
