Import("swiften_env", "env")

myenv = swiften_env.Clone()
myenv.MergeFlags(swiften_env["LIBIDN_FLAGS"])

objects = myenv.SwiftenObject([
			"StringPrep.cpp",
			"IDNA.cpp",
		])
swiften_env.Append(SWIFTEN_OBJECTS = [objects])

env.Append(UNITTEST_SOURCES = [
			File("UnitTest/StringPrepTest.cpp"),
	])
