SWIFTEN_SOURCES += \
  Swiften/EventLoop/EventOwner.cpp \
  Swiften/EventLoop/EventLoop.cpp \
  Swiften/EventLoop/SimpleEventLoop.cpp \
  Swiften/EventLoop/MainEventLoop.cpp

include Swiften/EventLoop/UnitTest/Makefile.inc
