Import("swiften_env")

sources = [
		"EventLoop.cpp",
		"EventOwner.cpp",
		"Event.cpp",
		"SimpleEventLoop.cpp",
	]

objects = swiften_env.SwiftenObject(sources)
swiften_env.Append(SWIFTEN_OBJECTS = [objects])

if swiften_env["PLATFORM"] == "darwin" :
	myenv = swiften_env.Clone()
	myenv.Append(CXXFLAGS = myenv["OBJCCFLAGS"])
	objects = myenv.SwiftenObject([
			"Cocoa/CocoaEventLoop.mm",
			"Cocoa/CocoaEvent.mm"
		])
	swiften_env.Append(SWIFTEN_OBJECTS = [objects])
