Import("swiften_env")

sources = [
		"EventLoop.cpp",
		"EventOwner.cpp",
		"MainEventLoop.cpp",
		"SimpleEventLoop.cpp",
	]

if swiften_env["PLATFORM"] == "darwin" and swiften_env["target"] == "native":
	sources += [
			"Cocoa/CocoaEventLoop.mm",
			"Cocoa/CocoaEvent.mm"
		]

objects = swiften_env.StaticObject(sources)
swiften_env.Append(SWIFTEN_OBJECTS = [objects])
