Import("swiften_env")

objects = swiften_env.SwiftenObject([
			"CapsInfoGenerator.cpp",
			"CapsManager.cpp",
			"EntityCapsManager.cpp",
			"EntityCapsProvider.cpp",
			"DummyEntityCapsProvider.cpp",
			"CapsStorage.cpp",
			"ClientDiscoManager.cpp",
			"DiscoInfoResponder.cpp",
			"JIDDiscoInfoResponder.cpp",
			"DiscoServiceWalker.cpp",
			"FeatureOracle.cpp",
		])
swiften_env.Append(SWIFTEN_OBJECTS = [objects])
