version: 2
jobs:
  build:
    working_directory: ~/swift
    docker:
      - image: tfar/swift-gcc:latest
    steps:
      - checkout
      - run:
          name: Version information
          command: |
            lsb_release -a
            qmake --version
      - run:
          name: Check basic source code style
          command: coala --non-interactive
      - run:
          name: Build and run unit tests
          # Disable QtUtilitiesTest.testDSTawareness test because it fails on this system.
          command: |
            export GTEST_FILTER=-QtUtilitiesTest.testDSTawareness
            ./scons test=unit max_jobs=0 allow_warnings=0 -j 2
