Import("env")

env.Append(UNITTEST_SOURCES = [
        File("LinkifyTest.cpp"),
        File("TabCompleteTest.cpp"),
        File("LastLineTrackerTest.cpp"),
    ])

if env["HAVE_HUNSPELL"] :
    env.Append(UNITTEST_SOURCES = [
        File("SpellParserTest.cpp"),
    ])
