SWIFTEN_SOURCES += \
	Swiften/Controllers/ChatController.cpp \
	Swiften/Controllers/ChatControllerBase.cpp \
	Swiften/Controllers/MainController.cpp \
	Swiften/Controllers/NickResolver.cpp \
	Swiften/Controllers/RosterController.cpp \
	Swiften/Controllers/XMPPRosterController.cpp \
	Swiften/Controllers/MUCController.cpp \
	Swiften/Controllers/EventController.cpp

include Swiften/Controllers/UnitTest/Makefile.inc
