SWIFTEN_SOURCES += \
	Swiften/Queries/IQRouter.cpp \
	Swiften/Queries/IQHandler.cpp \
	Swiften/Queries/IQChannel.cpp \
	Swiften/Queries/Request.cpp

include Swiften/Queries/Responders/Makefile.inc
include Swiften/Queries/UnitTest/Makefile.inc
