Import("env")

example_env = env.Clone()
example_env.MergeFlags(example_env["SWIFTEN_FLAGS"])
example_env.MergeFlags(example_env["SWIFTEN_DEP_FLAGS"])

for i in range(1,6) :
	example_env.Program("EchoBot" + str(i), ["EchoBot" + str(i) + ".cpp"])
example_env.Program("EchoComponent", "EchoComponent.cpp")
