import datetime

Import("env")

SConscript("Controllers/SConscript")

if env["SCONS_STAGE"] == "build" :
	if not GetOption("help") and not env.get("HAVE_OPENSSL", 0) :
		print "Error: Swift requires OpenSSL support, and OpenSSL was not found."
		Exit(1)

	if env["target"] == "native":
		 SConscript("QtUI/SConscript")
