SWIFTEN_OBJECTIVE_SOURCES += \
	Swiften/Application/MacOSX/MacOSXApplicationInitializer.mm \
	Swiften/Application/MacOSX/MacOSXApplicationMessageDisplay.mm

SWIFTEN_SOURCES += \
	Swiften/Application/MacOSX/MacOSXApplication.cpp
