Import("env")

################################################################################
# Flags
################################################################################

if env["SCONS_STAGE"] == "flags" :
	env["SLIMBER_FLAGS"] = {
			"LIBPATH": [Dir(".")],
			"LIBS": ["Slimber"]
		}

################################################################################
# Build
################################################################################

if env["SCONS_STAGE"] == "build" :
	myenv = env.Clone()
	myenv.MergeFlags(env["BOOST_FLAGS"])
	myenv.MergeFlags(env["SWIFTEN_FLAGS"])
	myenv.StaticLibrary("Slimber", [
			"LinkLocalPresenceManager.cpp",
			"FileVCardCollection.cpp",
			"VCardCollection.cpp",
			"Server.cpp",
			"MainController.cpp",
			"MenuletController.cpp",
			"Menulet.cpp"
		])

	env.Append(UNITTEST_SOURCES = [
			File("UnitTest/LinkLocalPresenceManagerTest.cpp"),
			File("UnitTest/MenuletControllerTest.cpp")
		])

	SConscript("CLI/SConscript")
	if env["PLATFORM"] == "darwin" :
		SConscript("Cocoa/SConscript")
	else :
		SConscript("Qt/SConscript")
