SWIFTEN_SOURCES += \
	Swiften/Elements/RosterPayload.cpp \
	Swiften/Elements/Payload.cpp \
	Swiften/Elements/Stanza.cpp \
	Swiften/Elements/Element.cpp \
	Swiften/Elements/DiscoInfo.cpp \
	Swiften/Elements/IQ.cpp

include Swiften/Elements/UnitTest/Makefile.inc
