SWIFTEN_SOURCES += \
	Swiften/Server/ServerSession.cpp \
	Swiften/Server/ServerFromClientSession.cpp \
	Swiften/Server/ServerStanzaRouter.cpp \
	Swiften/Server/IncomingConnection.cpp \
	Swiften/Server/UserRegistry.cpp \
	Swiften/Server/SimpleUserRegistry.cpp

include Swiften/Server/UnitTest/Makefile.inc
