Import("env")

if env["experimental"] :
	myenv = env.Clone()
	myenv.MergeFlags(myenv["SWIFTEN_FLAGS"])
	myenv.MergeFlags(myenv["SWIFTEN_DEP_FLAGS"])

	linkLocalTool = myenv.Program("NetworkTool", [
			"main.cpp"
		])
