UNITTEST_SOURCES += \
	Swiften/Parser/UnitTest/XMPPParserTest.cpp \
	Swiften/Parser/UnitTest/StanzaParserTest.cpp \
	Swiften/Parser/UnitTest/MessageParserTest.cpp \
	Swiften/Parser/UnitTest/PresenceParserTest.cpp \
	Swiften/Parser/UnitTest/IQParserTest.cpp \
	Swiften/Parser/UnitTest/StreamFeaturesParserTest.cpp \
	Swiften/Parser/UnitTest/SerializingParserTest.cpp \
  Swiften/Parser/UnitTest/XMLParserTest.cpp
