Import("env")

if env["SCONS_STAGE"] == "build" :
	myenv = env.Clone()
	myenv.BuildVersion("BuildVersion.h", project = "limber")
	myenv.MergeFlags(env["SWIFTEN_FLAGS"])
	myenv.MergeFlags(env["LIBIDN_FLAGS"])
	myenv.MergeFlags(env.get("LIBXML_FLAGS", ""))
	myenv.MergeFlags(env.get("EXPAT_FLAGS", ""))
	myenv.MergeFlags(env["OPENSSL_FLAGS"])
	myenv.MergeFlags(env["BOOST_FLAGS"])
	myenv.MergeFlags(myenv["PLATFORM_FLAGS"])

	myenv.Program("limber", ["main.cpp"])
