import os

Import("env")

myenv = env.Clone()
myenv.MergeFlags(env["SWIFTEN_FLAGS"])
myenv.MergeFlags(env["CPPUNIT_FLAGS"])
myenv.MergeFlags(env["BOOST_FLAGS"])
myenv.MergeFlags(env["LIBIDN_FLAGS"])

tester = myenv.Program("NetworkTest", [
		"BoostConnectionServerTest.cpp",
		"BoostConnectionTest.cpp",
		"DomainNameResolverTest.cpp",
		"#/QA/UnitTest/checker.cpp"
	])
clientTest = myenv.Alias("NetworkTest", tester, tester[0].abspath)
env.AlwaysBuild(clientTest)
