import os

Import("env")

if env["TEST"] :
	myenv = env.Clone()
	if "test_ipv6" in ARGUMENTS :
		myenv.Append(CPPDEFINES = ["TEST_IPV6"])
	myenv.MergeFlags(myenv["CHECKER_FLAGS"])
	myenv.MergeFlags(myenv["SWIFTEN_FLAGS"])
	myenv.MergeFlags(myenv["CPPUNIT_FLAGS"])
	myenv.MergeFlags(myenv["BOOST_FLAGS"])
	myenv.MergeFlags(myenv["LIBIDN_FLAGS"])
	myenv.MergeFlags(env["PLATFORM_FLAGS"])

	tester = myenv.Program("NetworkTest", [
			"BoostConnectionServerTest.cpp",
			"BoostConnectionTest.cpp",
			"DomainNameResolverTest.cpp",
		])
	myenv.Test(tester, "system", is_checker = True)
