Import("swiften_env")

SConscript(dirs = [
		"NetworkTest",
#		"ReconnectTest",
		"ClientTest",
#		"DNSSDTest",
		"StorageTest",
	])

if swiften_env.get("HAVE_OPENSSL", False) :
	SConscript(dirs = ["OpenSSLTest"])
