Import("swiften_env")

sources = [
		"ApplicationPathProvider.cpp",
	]

if swiften_env["PLATFORM"] == "darwin" and swiften_env["target"] == "native" :
	sources += [
			"CocoaApplication.mm",
			"MacOSXApplicationPathProvider.cpp",
		]
elif swiften_env["PLATFORM"] == "win32" :
	sources += [
			"WindowsApplicationPathProvider.cpp"
		]
else :
	sources += [
			"UnixApplicationPathProvider.cpp"
		]

objects = swiften_env.StaticObject(sources)
swiften_env.Append(SWIFTEN_OBJECTS = [objects])
