Import("swiften_env")

sources = [
		"Application.cpp",
		"ApplicationMessageDisplay.cpp",
	]

if swiften_env["PLATFORM"] == "darwin" and swiften_env["target"] == "native" :
	sources += [
			"MacOSX/MacOSXApplication.cpp",
			"MacOSX/MacOSXApplicationMessageDisplay.mm",
			"MacOSX/MacOSXApplicationInitializer.mm",
		]

objects = swiften_env.StaticObject(sources)
swiften_env.Append(SWIFTEN_OBJECTS = [objects])
