Import("swiften_env")

sources = [
		"Application.cpp",
		"ApplicationMessageDisplay.cpp",
		"ApplicationPathProvider.cpp",
	]

if swiften_env["PLATFORM"] == "darwin" and swiften_env["target"] == "native" :
	sources += [
			"MacOSX/MacOSXApplication.cpp",
			"MacOSX/MacOSXApplicationMessageDisplay.mm",
			"MacOSX/MacOSXApplicationInitializer.mm",
			"MacOSXApplicationPathProvider.cpp",
		]
elif swiften_env["PLATFORM"] == "win32" :
	sources += [
			"WindowsApplicationPathProvider.cpp"
		]

objects = swiften_env.StaticObject(sources)
swiften_env.Append(SWIFTEN_OBJECTS = [objects])
