import os

Import("env")

if env["TEST"] :
	myenv = env.Clone()
	myenv.MergeFlags(myenv["CHECKER_FLAGS"])
	myenv.MergeFlags(myenv["SWIFTOOLS_FLAGS"])
	myenv.MergeFlags(myenv["SWIFTEN_FLAGS"])
	myenv.MergeFlags(myenv["CPPUNIT_FLAGS"])
	myenv.MergeFlags(myenv["BOOST_FLAGS"])
	myenv.MergeFlags(myenv["LIBIDN_FLAGS"])
	if myenv.get("HAVE_OPENSSL") :
		myenv.MergeFlags(myenv["OPENSSL_FLAGS"])
		myenv.Append(CPPDEFINES = ["HAVE_OPENSSL"])
	myenv.MergeFlags(myenv["PLATFORM_FLAGS"])
	
	tester = myenv.Program("TLSTest", [
			"CertificateTest.cpp",
		])
	myenv.Test(tester, "system")
