Import("env")

if env["TEST"] :
	if env["SCONS_STAGE"] == "flags" :
			env["CHECKER_FLAGS"] = { 
					"LIBS": ["Checker"],
					"LIBPATH": [Dir(".")],
					"LINKFLAGS": ["/SUBSYSTEM:CONSOLE"] if env["PLATFORM"] == "win32" else []
				}

	if env["SCONS_STAGE"] == "build" :
			checker_env = env.Clone()
			checker_env.MergeFlags(env["BOOST_FLAGS"])
			checker_env.MergeFlags(env["CPPUNIT_FLAGS"])
			checker_env.Library("Checker", ["checker.cpp", "IO.cpp"])
