Import("env")

checker_env = env.Clone()
checker_env.MergeFlags(env["CPPUNIT_FLAGS"])
checker_env.Library("Checker", "checker.cpp")
env["CHECKER_FLAGS"] = { 
    "LIBS": ["Checker"],
    "LIBPATH": [Dir(".")],
		"LINKFLAGS": ["/SUBSYSTEM:CONSOLE"] if env["PLATFORM"] == "win32" else []
  }
