Import("swiften_env")

objects = swiften_env.SwiftenObject([
			"ByteArray.cpp",
			"DateTime.cpp",
			"SafeByteArray.cpp",
			"Error.cpp",
			"Log.cpp",
			"Paths.cpp",
			"String.cpp",
			"IDGenerator.cpp",
			"SimpleIDGenerator.cpp",
			"sleep.cpp",
		])
swiften_env.Append(SWIFTEN_OBJECTS = [objects])
