Import("swiften_env")

objects = swiften_env.StaticObject([
			"ByteArray.cpp",
			"Error.cpp",
			"Log.cpp",
			"Paths.cpp",
			"String.cpp",
			"IDGenerator.cpp",
			"sleep.cpp",
		])
swiften_env.Append(SWIFTEN_OBJECTS = [objects])
