Document: swift
Title: Debian swift Manual
Author: <insert document author here>
Abstract: This manual describes what swift is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/swift/swift.sgml.gz

Format: postscript
Files: /usr/share/doc/swift/swift.ps.gz

Format: text
Files: /usr/share/doc/swift/swift.text.gz

Format: HTML
Index: /usr/share/doc/swift/html/index.html
Files: /usr/share/doc/swift/html/*.html
