Import("swiften_env")

myenv = swiften_env.Clone()
myenv.MergeFlags(myenv["LIBIDN_FLAGS"])
myenv.MergeFlags(myenv["CARES_FLAGS"])

objects = myenv.StaticObject([
			"BoostConnection.cpp",
			"BoostConnectionFactory.cpp",
			"BoostConnectionServer.cpp",
			"MainBoostIOServiceThread.cpp",
			"BoostIOServiceThread.cpp",
			"ConnectionFactory.cpp",
			"ConnectionServer.cpp",
      "Connector.cpp",
			"TimerFactory.cpp",
			"BoostTimerFactory.cpp",
			"DomainNameResolver.cpp",
			"DomainNameAddressQuery.cpp",
			"DomainNameServiceQuery.cpp",
			"PlatformDomainNameResolver.cpp",
			"PlatformDomainNameServiceQuery.cpp",
			"CAresDomainNameResolver.cpp",
			"StaticDomainNameResolver.cpp",
			"HostAddress.cpp",
			"Timer.cpp",
			"BoostTimer.cpp",
		])
swiften_env.Append(SWIFTEN_OBJECTS = [objects])
