Import("swiftools_env")

myenv = swiftools_env.Clone()

sources = [
		"Notifier.cpp",
	]

if swiftools_env.get("HAVE_GROWL", False) :
	sources += [
			"GrowlNotifier.mm",
			"GrowlNotifierDelegate.mm",
		]
if swiftools_env.get("HAVE_SNARL", False) :
	myenv.MergeFlags(myenv["SNARL_FLAGS"])
	sources += [
			"SnarlNotifier.cpp",
		]
		
objects = myenv.StaticObject(sources)
swiftools_env.Append(SWIFTOOLS_OBJECTS = objects)
