import os

Import("env")

if env["TEST"] :
	myenv = env.Clone()
	myenv.MergeFlags(myenv["CHECKER_FLAGS"])
	myenv.MergeFlags(myenv["SWIFTOOLS_FLAGS"])
	myenv.MergeFlags(myenv["SWIFTEN_FLAGS"])
	myenv.MergeFlags(myenv["CPPUNIT_FLAGS"])
	myenv.MergeFlags(myenv["BOOST_FLAGS"])
	myenv.MergeFlags(myenv["LIBIDN_FLAGS"])
	myenv.MergeFlags(myenv.get("EXPAT_FLAGS", {}))
	myenv.MergeFlags(myenv.get("LIBXML_FLAGS", {}))
	myenv.MergeFlags(myenv["PLATFORM_FLAGS"])

	tester = myenv.Program("StorageTest", [
			"VCardFileStorageTest.cpp",
			"FileReadBytestreamTest.cpp",
		])
	myenv.Test(tester, "system", is_checker = True)
