Import("env")

myenv = env.Clone()
myenv.MergeFlags(env["SLIMBER_FLAGS"])
myenv.MergeFlags(env["SWIFTEN_FLAGS"])
myenv.MergeFlags(env["BOOST_FLAGS"])
myenv.MergeFlags(env.get("AVAHI_FLAGS", {}))

myenv.Program("slimber", [
		"main.cpp",
		"DummyMenulet.cpp",
	])
