import os

Import("env")

if env["TEST"] :
	myenv = env.Clone()
	myenv.MergeFlags(env["CHECKER_FLAGS"])
	myenv.MergeFlags(env["SWIFTEN_FLAGS"])
	myenv.MergeFlags(env["CPPUNIT_FLAGS"])
	myenv.MergeFlags(env["BOOST_FLAGS"])
	myenv.MergeFlags(env["LIBIDN_FLAGS"])

	tester = myenv.Program("NetworkTest", [
			"BoostConnectionServerTest.cpp",
			"BoostConnectionTest.cpp",
			"DomainNameResolverTest.cpp",
		])
	myenv.Test(tester, "system")
