Import("env")

myenv = env.Clone()
myenv.MergeFlags(myenv["SWIFTEN_FLAGS"])
myenv.MergeFlags(myenv["LIBIDN_FLAGS"])
myenv.MergeFlags(myenv["BOOST_FLAGS"])
myenv.MergeFlags(myenv["ZLIB_FLAGS"])
myenv.MergeFlags(myenv["OPENSSL_FLAGS"])
myenv.MergeFlags(myenv.get("SQLITE_FLAGS", {}))
myenv.MergeFlags(myenv.get("LIBXML_FLAGS", {}))
myenv.MergeFlags(myenv.get("EXPAT_FLAGS", {}))
myenv.MergeFlags(myenv.get("AVAHI_FLAGS", {}))
myenv.MergeFlags(myenv["PLATFORM_FLAGS"])

linkLocalTool = myenv.Program("LinkLocalTool", [
		"main.cpp"
	])
