Import("env")

myenv = env.Clone()
myenv.MergeFlags(env["SLIMBER_FLAGS"])
myenv.MergeFlags(env["SWIFTEN_FLAGS"])
myenv.MergeFlags(env["LIBIDN_FLAGS"])
myenv.MergeFlags(env["BOOST_FLAGS"])
myenv.Append(FRAMEWORKS = "Cocoa")

myenv.Program("Slimber", [
		"main.mm",
		"CocoaController.mm",
		"CocoaMenulet.mm",
		"CocoaAction.mm"
	])

myenv.Nib("MainMenu")
