Import("env")

if env["TEST"] :
	myenv = env.Clone()
	myenv.MergeFlags(myenv["SWIFTOOLS_FLAGS"])
	myenv.MergeFlags(myenv["SWIFTEN_FLAGS"])
	myenv.MergeFlags(myenv["BOOST_FLAGS"])
	if myenv["HAVE_XSS"] :
		myenv.MergeFlags(myenv.get("XSS_FLAGS", {}))
	tester = myenv.Program("IdleQuerierTest", ["IdleQuerierTest.cpp"])
