import os

Import("env")

if env["TEST"] :
	myenv = env.Clone()
	myenv.MergeFlags(myenv["CHECKER_FLAGS"])
	myenv.MergeFlags(myenv["SWIFTEN_FLAGS"])
	myenv.MergeFlags(myenv["CPPUNIT_FLAGS"])
	myenv.MergeFlags(myenv["BOOST_FLAGS"])
	myenv.MergeFlags(myenv["LIBIDN_FLAGS"])
	if myenv.get("HAVE_BONJOUR", 0) :
		myenv.Append(CPPDEFINES = "HAVE_BONJOUR")
	elif myenv.get("HAVE_AVAHI", 0) :
		myenv.Append(CPPDEFINES = ["HAVE_AVAHI"])
		myenv.MergeFlags(myenv["AVAHI_FLAGS"])

	tester = myenv.Program("DNSSDTest", [
			"DNSSDTest.cpp",
		])
	myenv.Test(tester, "system")
