UNITTEST_SOURCES += \
	Swiften/Serializer/PayloadSerializers/UnitTest/RosterSerializerTest.cpp \
	Swiften/Serializer/PayloadSerializers/UnitTest/ErrorSerializerTest.cpp \
	Swiften/Serializer/PayloadSerializers/UnitTest/CapsInfoSerializerTest.cpp \
	Swiften/Serializer/PayloadSerializers/UnitTest/ResourceBindSerializerTest.cpp \
	Swiften/Serializer/PayloadSerializers/UnitTest/PrioritySerializerTest.cpp \
	Swiften/Serializer/PayloadSerializers/UnitTest/DiscoInfoSerializerTest.cpp \
	Swiften/Serializer/PayloadSerializers/UnitTest/StatusSerializerTest.cpp \
	Swiften/Serializer/PayloadSerializers/UnitTest/StatusShowSerializerTest.cpp \
	Swiften/Serializer/PayloadSerializers/UnitTest/SoftwareVersionSerializerTest.cpp \
	Swiften/Serializer/PayloadSerializers/UnitTest/SecurityLabelSerializerTest.cpp \
	Swiften/Serializer/PayloadSerializers/UnitTest/SecurityLabelsCatalogSerializerTest.cpp
